### ISSUE TITLE
New version occurences

### ISSUE THREAD

**Issue by KJLJon** [tplaner/When#17]
Hello,

I like how in the older version (Master branch) you can keep on looping through the data until you get to a point you want to stop (endless events).

In the newer version (Development branch) it preloads up to 200 events into the occurrences array.  I think it would be nice to be able to not preload the events (if you choose to) and just endlessly loop through the data (until you want it to stop).

Otherwise, I think it works pretty good :+1:

**Comment by MattiJarvinen** [comment]
That is a major bummer. 

Most of the time 200 is quite enough, unless something recurs every workday for a couple of years.

**Comment by tplaner** [comment]
The workaround to this is to call the `count` method and set it to whatever you want. I'd avoid trying to get back more than 200 or so recurrences at a time for performance reasons though.

You shouldn't really need to either, because you can always use the last occurrence returned and make a new call with that as the `startDate`. If you need an example let me know.
