### ISSUE TITLE
Daylight Savings Time

### ISSUE THREAD

**Issue by joshstrange** [tplaner/When#32]
I hate DST with a passion but I have to support it in our app (we just switched over to RRules from a custom solution). Does your library handle DST at all or do you have any plans to support it? If not do you know of any workarounds people use to do this? Thanks! Love the library!

**Comment by tplaner** [comment]
I really need to do more research into this.

However, if you generate and store all of your times as UTC (Zulu) they will not be affected by DST.

You can then utilize PHP's DateTime, or a library like [Carbon](https://github.com/briannesbitt/carbon) to then translate the times into the appropriate TimeZone and handle DST (based on your users settings).

**Comment by joshstrange** [comment]
@tplaner Hmm, I'm not sure if that's true. We store all dates in UTC but for a repeating datetime DST does affect it. If I have a recurrence spanning the DST change then I need to adjust the UTC times to be +/-1hr depending on if it's in the spring or fall for the perceived time to stay the same. I've written some code to handle this transformation that takes a user's TZ to decided how to modify the start times that are generated from When and it might be too specific of a use-case to worry about but I do wonder how other companies handle this...

**Comment by larsRedia** [comment]
@joshstrange The When library actually handles DST transitions, but your dtstart needs to be of a certain type of timezone. According to https://wiki.php.net/rfc/datetime_and_daylight_saving_time, it is only zone type 3, that can make the correct calculations. As an example zone type 3 could be set with _DateTime('2011-09-13 14:15:16', new DateTimeZone('America/New_York'))_. And _DateTime('2011-09-13 14:15:16 -0400')_ would give you DateTime in a type 1 zone.
I had the same problem with events being 1 hour off when crossing DST start. But then i started setting the timezone on my dtstart DateTime objects to DateTimeZone('Europe/Copenhagen') and the problem was solved.
