### ISSUE TITLE
Error Message When including

### ISSUE THREAD

**Issue by codermjb** [tplaner/When#53]
I get this error when including the autoload.php from composer

Fatal error: Class 'When' not found in

I have done everything in the readme.md and added to composer.json file and installed.

**Comment by djamestaft** [comment]
$r = new \When\When();

i had frustration with this because I also tried the autoload statement which didn't work, but realized the way I was referencing when was wrong. Just do the whole $composer thing in terminal then you should be able to use it as stated above. Hope it helps...I WAS MISSING ONE BACKSLASH BEFORE WHEN!!!!!!
