### ISSUE TITLE
Exceptions

### ISSUE THREAD

**Issue by nicolasbuch** [tplaner/When#62]
Would be nice to have a possibility to be able to define explicit exceptions in a pattern before the generation of occurrences. This could be done by datetimeobjects or even patterns. See example of use down below

Example:
```php
// friday the 13th for the next 5 occurrences
$r = new When();
$r->startDate(new DateTime("19980213T090000"))
  ->freq("monthly")
  ->count(5)
  ->byday("fr")
  ->bymonthday(13)
  ->except([new Datetime(""), new Datetime("")])
  ->generateOccurrences();

print_r($r->occurrences);
```

$r->occurrences would of course return friday the 13th for the next 5 occurrences without the defined exeptions

**Comment by AmritGurung** [comment]
@tplaner  Any progress on this issue or any workaround where we could include a list of exceptions to remove certain occurrences?

It is quite common to have a repeating event that repeats every last week of a month, and there might be cases where the event organizer may want to remove certain occurrences of the event because of some festival or reason. The only way that is possible now is, if the organizer ends the current repeating event and create a new one from the next possible week with same pattern. Manually doing this for large records is not feasible and takes a lot of time.

**Comment by tplaner** [comment]
I'm willing to review any PR's with this functionality.

**Comment by PeterA** [comment]
Thanks for adding in support for exceptions! It looks like a followup would be to extend rrule() to support the [EXDATE](https://icalendar.org/iCalendar-RFC-5545/3-8-5-1-exception-date-times.html) property.
